name: Code Analysis

on:
  pull_request:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install Roslyn analyzers
      run: dotnet tool install --global dotnet-format

    - name: Run Roslyn format check
      run: dotnet format --verify-no-changes
