name: .NET Test Coverage

on: [push, pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'

    - name: Install dependencies
      run: dotnet restore DtaffingSolution/StaffingSolution.csproj

    - name: Install test dependencies
      run: dotnet restore StaffingSolutionTest/StaffingSolutionTest.csproj  
    
    - name: Run Tests with Coverage
      run: dotnet test StaffingSolutionTest/StaffingSolutionTest.csproj   /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage.info --filter FullyQualifiedName\!~Namespace.Of.Migrations
