name: Spell Checker

on: [push, pull_request]

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install codespell
      run: pip install codespell

    - name: Run codespell and save output to file
      run: |
        codespell --ignore-words-list="teh,informations" \
                  --skip="*.bin,*.dll,*.exe,*.obj,*.pdb,*.user,*.vscode,./StaffingSolution/wwwroot/css/,./StaffingSolution/Migrations/*" \
                  > spellcheck_report.txt || echo "Codespell found issues but continuing..."

    - name: Upload spellcheck report as artifact
      uses: actions/upload-artifact@master
      with:
        name: spellcheck-report
        path: spellcheck_report.txt


    - name: Restore dependencies
      run: dotnet restore
